ServerEvents.tags("item", event => {
    event.add("gtceu:circuits/mv", "mekanism:basic_control_circuit")
    event.add("gtceu:circuits/hv", "mekanism:advanced_control_circuit")
    event.add("gtceu:circuits/ev", "mekanism:elite_control_circuit")
    event.add("gtceu:circuits/iv", "mekanism:ultimate_control_circuit")
    event.add("gtceu:circuits/luv", "evolvedmekanism:overclocked_control_circuit")
    event.add("gtceu:circuits/zpm", "evolvedmekanism:quantum_control_circuit")
    event.add("gtceu:circuits/uv", "evolvedmekanism:dense_control_circuit")
    event.add("gtceu:circuits/uhv", "evolvedmekanism:multiversal_control_circuit")
    event.add("gtceu:circuits/uev", "mekanism_extras:absolute_control_circuit")
    event.add("gtceu:circuits/uiv", "mekanism_extras:supreme_control_circuit")
    event.add("gtceu:circuits/uxv", "mekanism_extras:cosmic_control_circuit")
    event.add("gtceu:circuits/opv", "mekanism_extras:infinite_control_circuit")
    event.add("gtceu:circuits/max", "evolvedmekanism:creative_control_circuit")
    event.add("gtceu:circuits/uv", "kubejs:optical_processor")
    event.add("gtceu:circuits/uhv", ["kubejs:exotic_processor", "kubejs:optical_assembly"])
    event.add("gtceu:circuits/uev", ["kubejs:cosmic_processor", "kubejs:exotic_assembly", "kubejs:optical_computer"])
    event.add("gtceu:circuits/uiv", ["kubejs:supracausal_processor", "kubejs:cosmic_assembly", "kubejs:exotic_computer"])
    event.add("gtceu:circuits/uxv", ["kubejs:supracausal_assembly", "kubejs:cosmic_computer", "kubejs:exotic_mainframe"])
    event.add("gtceu:circuits/opv", ["kubejs:supracausal_computer", "kubejs:cosmic_mainframe"])
    event.add("gtceu:circuits/max", "kubejs:supracausal_mainframe")
})