GTCEuStartupEvents.registry("gtceu:element", event => {
    event.create("insanitium")
        .protons(123)
        .neutrons(123)
        .halfLifeSeconds(-1)
        .decayTo(null)
        .symbol("Is")
        .isIsotope(false)

    event.create("sunium")
        .protons(1073741824)
        .neutrons(1073741824)
        .halfLifeSeconds(-1)
        .decayTo(null)
        .symbol("Su")
        .isIsotope(false)
})